// Copyright 2026 Matteo Fusi and Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef SIMO_MODULE_HH
#define SIMO_MODULE_HH

#include <Simo/core/Log.h>
#include <Simo/core/Time.h>

#include <string>

#include "Simo/core/InitializationStatus.h"
#include "Simo/parameter/ParameterTrie.h"
#include "Simo/port/Port.h"
#include "Simo/statistics/StatMapper.h"

namespace Simo {

class Context;

/// Collects parameters that are then passed to a Module instance
class SIMO_PUBLIC Parameters {
 public:
  virtual ~Parameters() = default;

  [[nodiscard]] std::string_view name() const;

  template <typename Self>
  Self& name(this Self& self, const std::string_view name) {
    self.name_ = name;
    return self;
  }

  // TODO make it to return a list of errors

  /// Implement checks on the set of parameters
  ///
  /// The default behavior is that everything is fine
  [[nodiscard]] virtual bool check() const;

  /// Create a new parameter with the given type and return a reference to it
  template <typename T>
  [[maybe_unused]]
  Parameter::ParameterTyped<T>& set(const std::string& name, const T& value) {
    return trie.add<T>(name, value);
  }

  /// Get a parameters with the given name.
  ///
  /// nullptr is returned if the type does not match or there is no parameter
  /// with this name
  template <typename T>
  [[nodiscard]] Parameter::ParameterTyped<T>* get(
      const std::string& name) const {
    return trie.find<T>(name);
  }

  [[nodiscard]] Parameter::Parameter* get(const std::string& name) const {
    return trie.find(name);
  }

  /// Get a set of parameters in a parameter subtree
  ///
  /// Parameters are organized in a tree-like structure (a trie), so it is
  /// possible to fetch a part of if. Return std::nullopt if the name does not
  /// match anything
  [[nodiscard]] std::optional<Parameters> get_subtree(
      const std::string& name) const;

 protected:
  Parameter::ParameterTrie trie;
  std::string name_;
};

/// A simulation unit that can schedule events in the context
///
/// Every class that inherits from module shall have a default constructor
/// (possibly trivial) and initialize everything in the initialize method.
class SIMO_PUBLIC Module {
 public:
  /// Associate a context to this instance and look at the parameters to
  /// initialize the structure. The default implementation is to return true.
  /// Derived classes can call <base_class>::initialize to initialize
  /// the attributes of the base class
  [[nodiscard]]
  virtual InitializationStatus initialize(Context& sim_ctx_v,
                                          const Parameters& parameters);

  [[nodiscard]] std::string_view name() const;

  [[nodiscard]] constexpr std::string name_of_child(
      const std::string_view child) const {
    return name_ + "/" + std::string(child);
  }

  [[nodiscard]] Context& sim_ctx() const;

  virtual ~Module() {}

  /// Record a statistic in a StatMapper to dump statistics
  void record_statistics(Statistics::StatMapper& mapper);

  [[nodiscard]] Port* get_port(std::string_view);

  Time current_time() const;

  template <typename Stat>
  Stat* get_statistic(const std::string_view name) {
    return statistics.get<Stat>(name);
  }

  template <typename Function>
  void visit_statistics(Function f) {
    statistics.visit(f);
  }

  /// Setup logging for the component
  ///
  /// Enable log by default when the operation succeeds. Calling this function
  /// will re-initialize the log even if the same out_file is passed
  virtual InitializationStatus log_setup(const std::filesystem::path& out_file);
  /// Default log_setup with default path set to Simo.log
  InitializationStatus log_setup();

  /// Enable/disable logging for the component
  void log_enable(bool new_value);

  void log_level(size_t level);
  void log_level(std::string_view level_name);

  /// Log a message with the given level. The message is generated by the
  /// callable. New-line is added
  ///
  /// The callable is evaluated only when the log is enabled and the log level
  /// is satisfied
  template <typename Callable>
  void log(size_t level, Callable&& callable) {
    auto f = [this, callable]() {
      return std::format("[{}] [{}] {}\n", current_time(), name(), callable());
    };
    log_raw_callable(level, true, f);
  }

  /// Log a message with the given level without adding timestamp
  template <typename Callable>
  void log_raw_callable(size_t level, bool print_level, Callable&& callable) {
    logger.log_callable(level, print_level, std::forward<Callable>(callable));
  }

  void populate_default_log_levels();

  Log::Logger& get_logger() { return logger; }

  /// Create a new statistic of type T
  template <typename T, typename... Args>
  T& create_statistic(Args... args) {
    T& s = statistics.emplace<T>(std::forward<Args>(args)...);
    return s;
  }

  /// Create a new port of type T
  template <typename T, typename... Args>
  T& create_port(const std::string_view name, Args... args) {
    auto ptr = std::make_unique<T>(std::forward<Args>(args)...);
    T& out_ref = *ptr;
    ports[std::string(name)] = std::move(ptr);
    return out_ref;
  }

  template <typename T, typename... Args>
  T& create_child(Args... args) {
    children.emplace_back(std::make_unique<T>(std::forward<Args>(args)...));
    return *children.back();
  }

 protected:
  Statistics::StatStorage statistics;
  std::unordered_map<std::string, std::unique_ptr<Port>> ports;
  std::vector<std::unique_ptr<Module>> children;
  Log::Logger logger;

 private:
  std::string name_;
  Context* sim_ctx_ = nullptr;
};
}  // namespace Simo

#endif  // SIMO_MODULE_HH